# Generated by Django 4.0.6 on 2022-07-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkapp', '0003_tag_order_customer_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tag',
            field=models.ManyToManyField(to='dkapp.tag'),
        ),
    ]
