# Generated by Django 4.0.6 on 2022-07-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkapp', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out of delivery', 'Out of delivery'), ('Delivereds', 'Delivereds')], max_length=200),
        ),
    ]
