# Generated by Django 3.1.4 on 2022-06-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('eid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('edata1', models.CharField(max_length=50)),
                ('edata2', models.CharField(max_length=50)),
            ],
        ),
    ]
