# Generated by Django 4.0.5 on 2022-06-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='edata1',
            new_name='data1',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='edata2',
            new_name='data2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='eid',
        ),
        migrations.AddField(
            model_name='entry',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
