# Generated by Django 4.0.5 on 2022-06-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_rename_edata1_entry_data1_rename_edata2_entry_data2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
