# Generated by Django 4.0.5 on 2022-06-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
    ]
