# Generated by Django 4.0.6 on 2022-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_alter_news_description_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='news_slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
