# Generated by Django 4.0.6 on 2022-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_remove_news_title_news_news_slug_news_news_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
