# Generated by Django 4.0.6 on 2022-07-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_alter_news_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_slug',
            field=models.SlugField(blank=True),
        ),
    ]
