# Generated by Django 3.1.4 on 2022-06-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(default='', null=True)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.CharField(max_length=50)),
                ('econtact', models.CharField(max_length=20)),
            ],
        ),
    ]
